version: '3.7'
services:
  pocketbase:
    image: spectado/pocketbase:0.19.14
    container_name: grimoire-pocketbase
    restart: unless-stopped
    ports:
      - '8090:80'
    volumes:
      - ./pb_data:/pb_data
      - ./pb_migrations:/usr/local/bin/pb_migrations/
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8090/api/health || exit 1
      interval: 5s
      timeout: 5s
      retries: 5
