name: ci

on:
  push:
    branches:
      - 'main'
    paths:
      - 'src/**'
      - 'static/**'
      - '.dockerignore'
      - 'build.sh'
      - 'docker-compose.yml'
      - 'Dockerfile'
      - 'package.json'
      - 'pnpm-lock.yaml'
      - 'postcss.config.cjs'
      - 'run-dev.sh'
      - 'svelte.config.js'
      - 'tailwind.config.cjs'
      - 'tsconfig.json'
      - 'vite.config.cjs'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: goniszewski/grimoire:latest
